### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by mgf909** [Senorsen/door-access-control#2]
HI - Can you advise if your software is for this hardware?
http://wiegand.com.cn/english/at_en/controllers.htm

**Comment by Senorsen** [comment]
Yes, it is. 

However because I have used only the 1-door access controller, there are some hard-coded values in the code, and so that it needs some improvements if you use more advanced one :-)

**Comment by mgf909** [comment]
Thank you for replying back to me.
I have the 4 door version of the controller. I updated the config.h with my controllers ip address, and the hex value of the SN across the two lines: ( i modified the values below for privacy )

#define DOOR_IPADDR "192.168.0.244"
#define DOOR_SN_1    0xFD           // DOOR-SN: 0xabcd (four hexadecimal num)
#define DOOR_SN_2    0xAA
#define DOOR_PORT    60000          // UDP Port: 60000

When i run it, it just times out...

root@hal:/haldata/doorcontrol/door-access-control# ./doorsend loopchk
[START] SENORSEN_ACCESS_CONTROL
Preparing data...
[INFO] setsockopt = 0
[ACTION] loopchk
[FUNCTION] loop_check_door
recvfrom error, may be network issues?
: Resource temporarily unavailable
recvfrom error, may be network issues?

Do you think this is because the code needs to be adjusted for the 4 door version?

Im not a programmer unfortunantly..so dont really understand the code.
Appreciate any help you can give - and thanks for your work already!

**Comment by Senorsen** [comment]
If we assume the IP address is correct and the code should work, I think maybe you can try to reverse the values of `DOOR_SN_1` and `DOOR_SN_2`? like this

```
#define DOOR_SN_1 0xAA // DOOR-SN: 0xabcd (four hexadecimal num)
#define DOOR_SN_2 0xFD
```

I'm not sure about this, but you can have a try... And thanks for your feedback.

**Note**: `make clean` may be needed, because a change in header file wouldn't be recompiled use a single `make` command.

**Comment by mgf909** [comment]
That worked!
 ( reversing the values. )

My goal is to monitor the controller and output the activity to an MQTT channel.

Thank you!

**Comment by Senorsen** [comment]
You are welcome. I'm very happy to see that works. :-)
